### ISSUE TITLE
Difficulties in loading the HiFi-GAN vocoder checkpoint 

### ISSUE THREAD

**Issue by Yassa777** [DiffPitcher/DiffPitcher#3]
I am having trouble running the DiffPitcher model using the provided code and checkpoints. I encountered the following issues:

The HiFi-GAN vocoder checkpoint file (g_05000000) is provided as a zip file. When I extract the contents of the zip file, I find the following files:

archive/data.pkl
archive/data
archive/version (Unix executable file)

I am unsure about how to properly load the vocoder checkpoint from these files.
When I point the hifi_path variable to the data.pkl file and try to load the checkpoint using torch.load(model_path, map_location=device), I encounter the following error:
Copy code_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
This suggests that the data.pkl file uses persistent IDs for serialization, but no persistent_load function is specified to handle these persistent IDs during deserialization.
I tried providing a custom persistent_load function to handle the persistent IDs, but I am still unable to successfully load the vocoder checkpoint.
The documentation and provided code do not clearly specify how to properly load the vocoder checkpoint from the extracted files and run inference using the DiffPitcher model.
I am unsure about the specific Python and PyTorch versions that are compatible with the provided code and checkpoints. The documentation does not mention the required versions, and I have been encountering compatibility issues.

I would greatly appreciate if you could provide guidance on the following:

How to properly load the HiFi-GAN vocoder checkpoint from the extracted files (data.pkl, data, version)?
How to handle the persistent IDs encountered during deserialization of the data.pkl file?
Are there any specific steps or modifications required to successfully run inference using the DiffPitcher model?
What are the recommended Python and PyTorch versions that are compatible with the provided code and checkpoints? Are there any specific version requirements or known compatibility issues?

I have been trying to run the code on a macOS system, but I am open to using other operating systems if necessary.
Please let me know if you need any additional information or if there are any specific files or code snippets you would like me to provide.
Thank you for your assistance!

**Comment by ambr-0-se** [comment]
Hi @Yassa777 , I also met the same problem. Can you share how do you fix the error? Thanks!

**Comment by ambr-0-se** [comment]
Hi @haidog-yaqub , could you specify the version of the libraries? This would help us a lot, thank you so much 🙏
