### ISSUE TITLE
LV2 plugin and other alternate formats

### ISSUE THREAD

**Issue by jofemodo** [DiffPitcher/DiffPitcher#5]
When you go forward with the plugin development, would you consider using a framework like [JUCE](https://github.com/juce-framework/JUCE) or [DPF](https://github.com/falkTX/DPF)? This would allow to make the plugin available in different formats, so it can be used in different computing platforms. For instance, we would like to test in the [zynthian](https://zynthian.org) platform, but we only support LV2 plugin format.

Thanks!

**Comment by haidog-yaqub** [comment]
> When you go forward with the plugin development, would you consider using a framework like [JUCE](https://github.com/juce-framework/JUCE) or [DPF](https://github.com/falkTX/DPF)? This would allow to make the plugin available in different formats, so it can be used in different computing platforms. For instance, we would like to test in the [zynthian](https://zynthian.org) platform, but we only support LV2 plugin format.
> 
> Thanks!

Thank you for your suggestion! However, we've decided to cancel the plugin development as the model requires a high-performance GPU, which isn't feasible for many platforms. Instead, we’re focusing on building a Hugging Face space, which will allow easier access and experimentation with the model.
